apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: visionguard-secrets
  labels:
    app: visionguard
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.secrets.storeName }}
    kind: ClusterSecretStore
  target:
    name: visionguard-app-secrets # This is the Kubernetes Secret that will be created
    creationPolicy: Owner
  data:
    # JWT and Auth
    - secretKey: JWT_SECRET
      remoteRef:
        key: {{ .Values.secrets.awsKey }}
        property: jwt_secret
    
    # SMTP
    - secretKey: SMTP_USER
      remoteRef:
        key: {{ .Values.secrets.awsKey }}
        property: smtp_user
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: {{ .Values.secrets.awsKey }}
        property: smtp_password
        
    # Default Admin Credentials
    - secretKey: ADMIN_DEFAULT_EMAIL
      remoteRef:
        key: {{ .Values.secrets.awsKey }}
        property: admin_default_email
    - secretKey: ADMIN_DEFAULT_PASSWORD
      remoteRef:
        key: {{ .Values.secrets.awsKey }}
        property: admin_default_password

    # MQTT Authentication
    - secretKey: MQTT_USERNAME
      remoteRef:
        key: {{ .Values.secrets.awsKey }}
        property: mqtt_username
    - secretKey: MQTT_PASSWORD
      remoteRef:
        key: {{ .Values.secrets.awsKey }}
        property: mqtt_password

    # AWS S3 Authentication (For Edge Alert Service)
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: {{ .Values.secrets.awsKey }}
        property: aws_access_key_id
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: {{ .Values.secrets.awsKey }}
        property: aws_secret_access_key
    - secretKey: AWS_REGION
      remoteRef:
        key: {{ .Values.secrets.awsKey }}
        property: aws_region
    - secretKey: S3_BUCKET
      remoteRef:
        key: {{ .Values.secrets.awsKey }}
        property: s3_bucket

    # Database URLs
    - secretKey: DATABASE_URL
      remoteRef:
        key: {{ .Values.secrets.awsKey }}
        property: database_url
