apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: nt505-q21-kltn-cluster-secret-store
spec:
  provider:
    aws:
      region: ap-southeast-1
      service: SecretsManager
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-operator
            namespace: kube-system
