apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-cluster-secret
  namespace: postgres
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: nt505-q21-kltn-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: postgres-cluster-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: NT505.Q21-KLTN
        property: postgres-username
    - secretKey: password
      remoteRef:
        key: NT505.Q21-KLTN
        property: postgres-password
