apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: "*"
    helm:
      values: |
        serviceAccount:
          name: external-secrets-operator
          annotations:
            "eks.amazonaws.com/role-arn": arn:aws:iam::559947225003:role/KLTN-EKS-ExternalSecretsOperatorRole
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

