apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plugin-barman-cloud
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres
  source:
    repoURL: https://cloudnative-pg.github.io/charts
    chart: plugin-barman-cloud
    targetRevision: "*"
    helm:
      values: |
        serviceAccount:
          create: true
          name: postgres-cluster
          annotations:
            "eks.amazonaws.com/role-arn": arn:aws:iam::559947225003:role/KLTN-EKS-CNPGRole
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

