name: Feature Component Pipeline

on:
  push:
    branches:
      - "feat/**"
      - "bugfix/**"

jobs:
  changes:
    name: Detect Changed Components
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Path Filter (Detect Changed Components)
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend:
              - 'app/frontend/**'
            user-service:
              - 'app/services/user-service/**'
            device-service:
              - 'app/services/device-service/**'
            alert-service:
              - 'app/services/alert-service/**'
            signaling-service:
              - 'app/services/signaling-service/**'

  global-scanner:
    name: Global Scanner
    needs: changes
    if: needs.changes.outputs.services != '[]' # Run only if there are changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: SonarQube Validation
        uses: sonarsource/sonarqube-scan-action@master
        with:
          args: >-
            -Dsonar.organization=kusanali3110
            -Dsonar.projectKey=kusanali3110_NT505.Q21-KLTN
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  feature-build-scan:
    name: CI/CD Pipeline - ${{ matrix.service }}
    needs: changes
    if: needs.changes.outputs.services != '[]'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # If 1 service fails, other parallel services will not be forced to stop
      matrix:
        service: ${{ fromJSON(needs.changes.outputs.services) }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Resolve Environment Parameters
        id: compute
        run: |
          # Dynamic parameter planning based on the value of matrix.service (Node.js or Python)
          if [ "${{ matrix.service }}" == "frontend" ]; then
            echo "SRC_PATH=app/frontend" >> $GITHUB_ENV
            echo "DOCKER_CTX=app/frontend" >> $GITHUB_ENV
            echo "DOCKER_FILE=app/frontend/Dockerfile" >> $GITHUB_ENV
            echo "TECH_STACK=node" >> $GITHUB_ENV
          else
            echo "SRC_PATH=app/services/${{ matrix.service }}" >> $GITHUB_ENV
            echo "DOCKER_CTX=app" >> $GITHUB_ENV
            echo "DOCKER_FILE=app/services/${{ matrix.service }}/Dockerfile" >> $GITHUB_ENV
            echo "TECH_STACK=python" >> $GITHUB_ENV
          fi

          # Format Tag name: Remove / from branch name, create safe-name and append with 7-digit Git SHA (e.g., feat-frontend-f43ab1a)
          SAFE_BRANCH=$(echo "${{ github.ref_name }}" | tr '/' '-')
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          TAG="$SAFE_BRANCH-$SHORT_SHA"
          REPO="${{ secrets.DOCKERHUB_USERNAME }}/app-${{ matrix.service }}"

          echo "tag_name=$REPO:$TAG" >> $GITHUB_ENV

      - name: Environment Setup (Node.js)
        uses: actions/setup-node@v3
        if: env.TECH_STACK == 'node'
        with:
          node-version: "22"

      - name: Environment Setup (Python)
        uses: actions/setup-python@v4
        if: env.TECH_STACK == 'python'
        with:
          python-version: "3.10"

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Snyk SCA Local Scanner
        run: |
          cd ${{ env.SRC_PATH }}
          if [ "${{ env.TECH_STACK }}" == "node" ]; then
            npm ci
            snyk test --all-projects
          else
            pip install -r requirements.txt
            snyk test --file=requirements.txt
          fi
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Initialize Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub Target Space
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Assemble Docker Package (Load to local daemon)
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.DOCKER_CTX }}
          file: ${{ env.DOCKER_FILE }}
          push: false # Don't push to cloud immediately
          load: true # Must load=true for Trivy to scan
          tags: ${{ env.tag_name }}
          build-args: |
            VITE_API_GATEWAY_URL=${{ vars.VITE_API_GATEWAY_URL }}

      - name: Trivy Integrity & Container OS Scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.tag_name }}
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

      - name: Push Protected Tag to Registry
        if: success()
        run: |
          docker push ${{ env.tag_name }}
          echo "==== FEATURE DEPLOYMENT SUCCESS ===="
          echo "Docker Image: ${{ env.tag_name }}"
