name: Feature Component Pipeline

on:
  push:
    branches:
      - "feat/**"
      - "bugfix/**"

jobs:
  changes:
    name: Detect Changed Components
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Path Filter (Detect Changed Components)
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend:
              - 'app/frontend/**'
            user-service:
              - 'app/services/user-service/**'
            device-service:
              - 'app/services/device-service/**'
            alert-service:
              - 'app/services/alert-service/**'
            signaling-service:
              - 'app/services/signaling-service/**'

  global-scanner:
    name: Global Scanner
    needs: changes
    if: needs.changes.outputs.services != '[]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: SonarQube Validation
        uses: sonarsource/sonarqube-scan-action@master
        with:
          args: >-
            -Dsonar.organization=kusanali3110
            -Dsonar.projectKey=kusanali3110_NT505.Q21-KLTN
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  feature-scan:
    name: Source Code Scan - ${{ matrix.service }}
    needs: changes
    if: needs.changes.outputs.services != '[]'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJSON(needs.changes.outputs.services) }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Resolve Environment Parameters
        id: compute
        run: |
          if [ "${{ matrix.service }}" == "frontend" ]; then
            echo "SRC_PATH=app/frontend" >> $GITHUB_ENV
            echo "TECH_STACK=node" >> $GITHUB_ENV
          else
            echo "SRC_PATH=app/services/${{ matrix.service }}" >> $GITHUB_ENV
            echo "TECH_STACK=python" >> $GITHUB_ENV
          fi

      - name: Environment Setup (Node.js)
        uses: actions/setup-node@v3
        if: env.TECH_STACK == 'node'
        with:
          node-version: "22"

      - name: Environment Setup (Python)
        uses: actions/setup-python@v4
        if: env.TECH_STACK == 'python'
        with:
          python-version: "3.10"

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Snyk SCA Local Scanner
        run: |
          cd ${{ env.SRC_PATH }}
          if [ "${{ env.TECH_STACK }}" == "node" ]; then
            npm ci
            snyk test --all-projects
          else
            pip install -r requirements.txt
            snyk test --file=requirements.txt
          fi
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
